blueprint:
  name: Flash Lights Red
  description: >
     Turn on light when motion is detected
  domain: automation
  source_url: https://github.com/k-u-i-p/HomeAssistant/edit/main/Lights_Alarm.yaml
  input:
    activated:
        name: Activated
        description: "Sensor to activate lights."
        selector:
            entity:
    presense:
        name: Presense
        description: "When these people aren't home."
        selector:
            entity: device_tracker
    target_lights:
        name: Lights
        description: "lights to flash"
        selector:
          target:
            entity:
              domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input activated
    to: 'on'
    for: 00:00:05

variables:
  activated: !input activated
  target_lights: !input target_lights
  presense: !input presense

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: device_tracker.ben
      state: "away"
  
action:
  - service: light.turn_on
    target: !input target_lights
    data:
      entity_id: scene.all_lights_snapshot
      brightness: 255
      color_name: "red"
      flash: long
